### ISSUE TITLE
Threadpool 

### ISSUE THREAD

**Issue by Empty-Code** [thames1000/jqr_library#1]
Remove `pthread_condattr_t cattr;`
change
```
  tpool->mutex = (pthread_mutex_t)PTHREAD_MUTEX_INITIALIZER;
  tpool->condition = (pthread_cond_t)PTHREAD_COND_INITIALIZER;
```
to use `pthread_mutex_init()` and `pthread_cond_init()`

Destroy mutexes in `tpool_init()`
In `*startThread` make sure value `*tpool` is not `NULL`
In `*startThread` make sure to use `free()` on the `*arg`
In `tpool_destroy` make sure to use `pthread_mutex_destroy()` and `pthread_cond_destroy()` on mutexes.
In `tpool_add_work` make sure to check if `calloc()` returned `NULL`

**Comment by thames1000** [comment]
Thread pool updated
